version: '3.3'

networks:
  backend:
    driver: bridge

services:

  api:
    build:
      context: ./api
      args:
        - NODE_ENV=development
        - NODE_VERSION=10.16.3
    volumes:
      - ../api:/opt/app
    networks:
      - backend
    entrypoint: run "yarn dev"
    tty: true
    restart: always

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../data/logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    depends_on:
      - api
    tty: true
    restart: always

  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongodata:/bitnami
    environment:
      - "MONGODB_ROOT_PASSWORD=root"
      - "MONGODB_USERNAME=user"
      - "MONGODB_PASSWORD=pass"
      - "MONGODB_DATABASE=api"

  neo4j:
    image: 'bitnami/neo4j:latest'
    networks:
      - backend
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - ../data:/bitnami

volumes:
  mongodata: