version: '3.3'

networks:
  api_backend:
    driver: bridge
  proxy:
    external: true

services:

  api:
    build:
      context: ./api
      args:
        - NODE_ENV=production
        - NODE_VERSION=10.16.3
    volumes:
      - ../api:/opt/app
    networks:
      - api_backend
    entrypoint: run "yarn start"
    tty: true
    restart: always

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../data/logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
    networks:
      - api_backend
      - proxy
    depends_on:
      - api
    tty: true
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.desm.tech`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=mytlschallenge"

  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    networks:
      - api_backend
    volumes:
      - ../data:/bitnami
    environment:
      - "MONGODB_ROOT_PASSWORD=root"
      - "MONGODB_USERNAME=user"
      - "MONGODB_PASSWORD=pass"
      - "MONGODB_DATABASE=api"

  neo4j:
    image: 'bitnami/neo4j:latest'
    networks:
      - api_backend
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - ../data:/bitnami